name: Welcome New Contributors

on:
	pull_request_target:
		types: [opened]

	jobs:
		welcome:
			runs-on: ubuntu-latest
			steps:
			  -uses: actions/first-interaction@v1
			   with: 
				repo-token: ${{ secrets.GITHUB_TOKEN }}
				pr-message: 'Thankyoy for your pull req.'

